# Generated by Django 5.1.5 on 2025-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
