# Generated by Django 5.1.5 on 2025-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_history_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
