# Generated by Django 5.1.5 on 2025-02-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notification_target_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('narrator', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='audiobooks/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='main.book')),
            ],
        ),
    ]
