# Generated by Django 5.1.5 on 2025-02-22 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_audiobook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='file',
            field=models.FileField(upload_to='audiobooks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'flac'])]),
        ),
    ]
