# Generated by Django 5.1.5 on 2025-02-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_audiobook_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='file',
            field=models.FileField(upload_to='audiobooks/'),
        ),
    ]
