# Generated by Django 5.1.5 on 2025-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_book_language_booktranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='Public', max_length=50),
        ),
    ]
