# Generated by Django 5.1.5 on 2025-03-01 12:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_book_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('public_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
