# Generated by Django 5.1.5 on 2025-03-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_book_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
