# Generated by Django 5.1.5 on 2025-03-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_readingtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='published_date',
        ),
    ]
