# Generated by Django 5.1.5 on 2025-07-20 15:40

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_comment_news_alter_comment_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('story', django_ckeditor_5.fields.CKEditor5Field()),
                ('country', models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, choices=[('1-3 days', '1-3 days'), ('4-7 days', '4-7 days'), ('1-2 weeks', '1-2 weeks'), ('2+ weeks', '2+ weeks')], max_length=50, null=True)),
                ('season', models.CharField(blank=True, choices=[('Spring', 'Spring')], max_length=50, null=True)),
                ('budget_level', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury')], max_length=50, null=True)),
                ('pro_tips', django_ckeditor_5.fields.CKEditor5Field()),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='main.travelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_images/')),
                ('travel_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.travelstory')),
            ],
        ),
    ]
