# Generated by Django 5.1.5 on 2025-07-20 16:10

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_travelcategory_travelstory_travelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelstory',
            name='budget_level',
            field=models.CharField(blank=True, choices=[('budget', 'Budget ($)'), ('mid-range', 'Mid-range ($$)'), ('luxury', 'Luxury ($$$)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='main.travelcategory'),
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='country',
            field=models.CharField(blank=True, choices=[('usa', 'United States'), ('uk', 'United Kingdom'), ('france', 'France'), ('japan', 'Japan'), ('australia', 'Australia'), ('thailand', 'Thailand'), ('peru', 'Peru'), ('south-africa', 'South Africa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-3', '1-3 days'), ('4-7', '4-7 days'), ('1-2', '1-2 weeks'), ('2+', '2+ weeks')], default=datetime.datetime(2025, 7, 20, 16, 9, 51, 849602, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='pro_tips',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Pro Tips'),
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall/Autumn'), ('winter', 'Winter')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='story',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='travelstory',
            name='tags',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
