# Generated by Django 5.1.5 on 2025-07-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_travelstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='travel_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='main.travelstory'),
        ),
    ]
