# Generated by Django 5.1.5 on 2025-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_comment_travel_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
