# Generated by Django 5.1.5 on 2025-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_newscategory_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelstory',
            name='thumbnail',
            field=models.ImageField(default='default_imgs/travel.jpg', upload_to='travel_images/'),
        ),
    ]
