# Generated by Django 5.1.5 on 2025-08-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_objview_delete_bookview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objview',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_views', to='main.news'),
        ),
        migrations.AlterField(
            model_name='objview',
            name='travel_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_story_views', to='main.travelstory'),
        ),
    ]
