# Generated by Django 5.1.5 on 2025-08-19 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_objview_news_alter_objview_travel_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(db_index=True, default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-views'], name='book_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-published_date'], name='book_published_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', '-views'], name='book_status_views_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', '-published_date'], name='book_status_published_idx'),
        ),
    ]
