# Generated by Django 5.1.5 on 2025-08-19 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_add_book_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='objview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-views'], name='news_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_date'], name='news_published_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='objview',
            index=models.Index(fields=['book', '-created_at'], name='objview_book_created_idx'),
        ),
        migrations.AddIndex(
            model_name='objview',
            index=models.Index(fields=['news', '-created_at'], name='objview_news_created_idx'),
        ),
        migrations.AddIndex(
            model_name='objview',
            index=models.Index(fields=['travel_story', '-created_at'], name='objview_travel_created_idx'),
        ),
        migrations.AddIndex(
            model_name='objview',
            index=models.Index(fields=['user', '-created_at'], name='objview_user_created_idx'),
        ),
    ]
