# Generated by Django 5.1.5 on 2025-08-20 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_fix_view_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='book_published_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='book_status_published_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='news_published_desc_idx',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='book_published_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', '-created_at'], name='book_status_published_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-created_at'], name='news_published_desc_idx'),
        ),
    ]
