# Generated by Django 5.1.5 on 2025-08-21 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_published_date_to_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelstory',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_travel_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelstory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_travel_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
